//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortMan2014
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PORTMAN2014Entities : DbContext
    {
        public PORTMAN2014Entities()
            : base("name=PORTMAN2014Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableGroup> TableGroup { get; set; }
        public virtual DbSet<TableParameter> TableParameter { get; set; }
        public virtual DbSet<TablePortAlcatel> TablePortAlcatel { get; set; }
        public virtual DbSet<TablePortAvea> TablePortAvea { get; set; }
        public virtual DbSet<TableRouterAlcatel> TableRouterAlcatel { get; set; }
        public virtual DbSet<TableRouterCisco> TableRouterCisco { get; set; }
        public virtual DbSet<TableRouterHuawei> TableRouterHuawei { get; set; }
        public virtual DbSet<TableSession> TableSession { get; set; }
        public virtual DbSet<TableUser> TableUser { get; set; }
    }
}
