//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortMan2014
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableGroup
    {
        public TableGroup()
        {
            this.TableUser = new HashSet<TableUser>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<TableUser> TableUser { get; set; }
    }
}
