//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortMan2014
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePortAvea
    {
        public int ID { get; set; }
        public string PortType { get; set; }
        public string SiteName { get; set; }
        public string SiteIP { get; set; }
        public string PortName { get; set; }
        public string Description { get; set; }
        public string PRTType { get; set; }
        public string SFPType { get; set; }
        public string OprState { get; set; }
        public string AdmState { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UpdateUsername { get; set; }
        public string Status { get; set; }
        public string Logs { get; set; }
        public string ReservDescription { get; set; }
        public string RequestUser { get; set; }
    }
}
