//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortMan2014
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePortAlcatel
    {
        public int ID { get; set; }
        public string SiteName { get; set; }
        public string SiteId { get; set; }
        public string SnmpPortId { get; set; }
        public string SfpOpticalCompliance { get; set; }
        public string SfpStatus { get; set; }
        public string PortCategory { get; set; }
        public string SpecificType { get; set; }
        public string Description { get; set; }
        public string ReservDescription { get; set; }
        public string State { get; set; }
        public string DisplayedName { get; set; }
        public string OperationalState { get; set; }
        public string AdministrativeState { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UpdateUsername { get; set; }
        public string Status { get; set; }
        public string Logs { get; set; }
    }
}
